- name: Installation du cron job
  ansible.builtin.cron:
    # Note that Grav will say there is no scheduler installed
    # because it is looking for an exact command line in crontab...
    name: grav-scheduler
    job: "php{{ php_version }} bin/grav scheduler 1>> /dev/null 2>&1"
    user: "{{ grav_owner }}"
    state: present

- name: Configuration de la variable HOME du cron job
  ansible.builtin.cron:
    name: HOME
    value: /var/www/{{ grav_owner }}/dist
    user: "{{ grav_owner }}"
    state: present
    env: true

- name: Configuration de la variable PATH du cron job
  ansible.builtin.cron:
    name: PATH
    value: "/usr/local/bin:/usr/bin"
    user: "{{ grav_owner }}"
    state: present
    env: true
