authentik_secret_key: "{{ vault_authentik_secret_key }}"

authentik_proxy_trusted: "2001:913:1000:11::11/128,2001:913:1000:11::12/128,10.0.11.11/32,10.0.11.12/32"
authentik_mail_from: "Neutrinet SSO <noreply@neutrinet.be>"

authentik_postgresql_password: "{{ vault_authentik_postgresql_password }}"
authentik_postgresql_host: haproxy-00.patata.louise.neutri.net

authentik_s3_access_key: "{{ vault_authentik_s3_access_key }}"
authentik_s3_secret_key: "{{ vault_authentik_s3_secret_key }}"

rclone_backup_host: s3.fr-par.scw.cloud
rclone_backup_bucket: neutrinet-authentik
rclone_backup_provider: scaleway
rclone_backup_access_key: "{{ vault_rclone_backup_access_key }}"
rclone_backup_secret_key: "{{ vault_rclone_backup_secret_key }}"
rclone_backup_region: fr-par
rclone_backup_storage_class: ONEZONE_IA

rclone_backup_encryption_password: "{{ vault_rclone_backup_encryption_password }}"
rclone_backup_encryption_salt: "{{ vault_rclone_backup_encryption_salt }}"
