---
- name: Prepare
  hosts: all
  become: true

  pre_tasks:
    - name: Mise Ã  jour du cache APT
      apt:
        update_cache: true

    - name: Installation des ACL
      package:
        name: acl
        state: present

    - name: Installation de Git
      package:
        name: git
        state: present

  roles:
    - telegraf
    - postgres_standalone
