dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: bookworm-knot-primary-molecule
    box: debian/bookworm64
    cpu: 2
    memory: 512
    interfaces:
      - network_name: private_network
        ip: 172.29.129.41
        auto_config: true
  - name: bookworm-knot-secondary-molecule
    box: debian/bookworm64
    cpu: 2
    memory: 512
    interfaces:
      - network_name: private_network
        ip: 172.29.129.42
        auto_config: true
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: /usr/bin/python3
    ssh_connection:
      pipelining: true
verifier:
  name: ansible
