- name: Installation de Prometheus
  package:
    name: prometheus
    state: present

- name: Configuration de l'environnement de Prometheus
  template:
    src: prometheus/prometheus.env.j2
    dest: /etc/default/prometheus
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  notify: restart prometheus

- name: Configuration de Prometheus
  template:
    src: prometheus/prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: "u=rw,g=r,o="
    validate: promtool check config %s
  notify: reload prometheus

- name: Création du répertoire des jobs
  file:
    path: /etc/prometheus/conf.d
    owner: prometheus
    group: prometheus
    mode: "u=rwx,go=rx"
    state: directory

- name: Activation de Prometheus au démarrage
  service:
    name: prometheus
    state: started
    enabled: yes

- name: Trigger Prometheus handlers
  meta: flush_handlers
