knot_mode: secondary  # or primary
knot_primary_server_ssh: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDBgX7Xb5aI8aKl0trZiJWhTgegcJ+cShVC+OHgqCaHi2io37otXqIR7j211FowS/c9r466VlbCAdqmT41l4G0fQjltdnQzkbAtAc04n0+yDouDW98n+KIbwZCt9RgC1k7OTVuPzJ6E78aXoeUvU33qbT2hHMlJyxl77P6Zhk5jtEtXq8neTFPyAk1WzVHoatFYUlReKJS09SAgl49yY90KA/vxMOYUJF01ER7Yv1/gK1x0/FDvXDaFDQWEg0XpQ6r6EXm5AyZ6AYJ9kKxjqdHDNPLK56EKaD9cxbjlwLvshWQjcqHR51RmUhnNLsl16nddrmr0Fpr/hvlhcssPsDZNfRgxi3gleY3zhJwL3g5h3m45bbMsOKrygIbu8njF6MzxrQbfTWZKeGxG5YOBN7GcJRAE8826aIb6Hv3Kei9RvtLsxJLaM61F8M4Br5c1N6aCB7xXbweXBTEZzooh5CUi+9E83NUq0catobYa6GSRayOZGEhcFXBsvt+QCrJ5H2E="

knot_primary_serveur: ::1
knot_secondary_serveurs:
  - ::1
knot_vpn_servers:
  - ::1

# keymgr -t acmebot_key hmac-sha512
knot_vpn_server_key: M30oTBIy34RJoJcpNyd2tzEfCjxl73yzXxe4vdSjN4h5c9n6ADJvxMffYHUqV0msOtJXou1HA7uw18cywW0Qbg==
knot_secondary_server_key: M30oTBIy34RJoJcpNyd2tzEfCjxl73yzXxe4vdSjN4h5c9n6ADJvxMffYHUqV0msOtJXou1HA7uw18cywW0Qbg==

knot_zone_arpa:
  - 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa

knot_reverse_domain: localhost
knot_reverse_networks:
  - ::1/128
