---

- name: Ajout de la clé GPG de Docker dans APT
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    owner: root
    group: root
    mode: "ugo=r"
    force: true

- name: Ajout du dépôt APT pour Docker
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release | lower }} stable
    filename: docker
    state: present

- name: Installation de Docker
  ansible.builtin.package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Installation des dépendances python
  ansible.builtin.package:
    name: python3-docker
    state: present

- name: Configuration de Docker
  ansible.builtin.copy:
    src: docker/daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: "u=rw,go=r"
  notify: Restart docker

- name: Activation de Docker au démarrage
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Création d'un cron job pour nettoyer les images docker chaque semaine
  ansible.builtin.cron:
    name: docker-prune
    cron_file: docker-prune
    state: present
    special_time: weekly
    user: root
    job: docker system prune -af --filter "until=$((30*24))h" > /dev/null

- name: Trigger haproxy handler
  ansible.builtin.meta: flush_handlers

- name: Ajouts de l'utilisateur telegraf au group docker
  ansible.builtin.user:
    name: telegraf
    groups: docker
    append: true
  notify: Restart telegraf
  tags: ['telegraf_config']

- name: Installation des plugins Telegraf
  ansible.builtin.template:
    src: telegraf/docker.conf.j2
    dest: /etc/telegraf/telegraf.d/docker.conf
    owner: telegraf
    group: telegraf
    mode: "u=rw,g=r,o="
    validate: telegraf --config %s --test
  notify: Restart telegraf
  tags: ['telegraf_config']

- name: Configuration des backups Borgmatic
  ansible.builtin.template:
    src: borgmatic/docker.yml.j2
    dest: /etc/borgmatic.d/docker.yml
    owner: root
    group: root
    mode: "u=rw,go="
    validate: borgmatic config validate --show -c %s
  tags: ['borgmatic_config']
