---
- name: Création du /var/www pour l'utilisateur caddy
  ansible.builtin.file:
    path: /var/www
    owner: caddy
    group: caddy
    mode: "u=rwx,go=rx"
    state: directory

- name: Création du dossier /var/www/{{ web_app_owner }}/dist
  ansible.builtin.file:
    path: /var/www/{{ web_app_owner }}/dist
    owner: "{{ web_app_owner }}"
    group: "{{ web_app_owner }}"
    mode: "u=rwx,go=rx"
    state: directory
